CREATE TABLE LOYALTY(
  id INT PRIMARY KEY AUTO_INCREMENT,
  barcode INT NOT NULL,
  bonusPoints INT
);

ALTER TABLE CUSTOMERS
    ADD COLUMN loyalty_id INT;

ALTER TABLE CUSTOMERS
    ADD CONSTRAINT FK_loyaltyId FOREIGN KEY (loyalty_id) REFERENCES LOYALTY(id);